import type { Metadata } from "next";
import { Header } from "@/shared/components/shared/header";
import { Container } from "@/shared/components/shared";

export const metadata: Metadata = {
  title: "Next Pizza | Checkout",
  description: "Generated by create next app",
};

export default async function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header
          hasCart={false}
          hasSearch={false}
          className="border-gray-200 border-b-gray-200"
        />
        {children}
      </Container>
    </main>
  );
}
